--(Whitelist)
CREATE TABLE public.authorized_users (
    email TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    alias TEXT UNIQUE NOT NULL,
    is_admin BOOLEAN NOT NULL DEFAULT FALSE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- USERS TABLE (Users logged and Credit Control)
CREATE TABLE public.Users (
    id UUID PRIMARY KEY
        REFERENCES auth.users(id)
        ON DELETE CASCADE,
    email TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    alias TEXT UNIQUE NOT NULL,
    phoneNumber TEXT,
    hasPaidEntry BOOLEAN NOT NULL DEFAULT FALSE,
    availablePoolCredits INT NOT NULL DEFAULT 0,
    isAdmin BOOLEAN NOT NULL DEFAULT FALSE,
    createdAt TIMESTAMPTZ NOT NULL DEFAULT NOW()
);



-- MATCH RESULTS 
-- Resultados oficiales de cada partido
CREATE TABLE public.MatchResults (
    matchId TEXT PRIMARY KEY,          -- Unique ID (e.g., 'A1', 'B3', 'FINAL')
    team1 TEXT NOT NULL,
    team2 TEXT NOT NULL,
    goal1 INT DEFAULT NULL,             -- NULL means the match hasn't been played/finished yet
    goal2 INT DEFAULT NULL,
    matchStatus TEXT NOT NULL DEFAULT 'PENDING'
        CHECK (
            matchStatus IN (
                'PENDING',
                'FINISHED',
                'CANCELED'
            )
        ),    -- 'PENDING' Pending, 'FINISHED' Finished, 'CANCELED' Canceled
    hasExtraPool BOOLEAN NOT NULL DEFAULT FALSE,
    scheduleAt TIMESTAMPTZ NULL  -- hora exacta del partido
);
-- =====================================================
-- MATCH BETS
-- =====================================================
-- Se permiten múltiples apuestas por usuario
-- para el mismo partido.
-- Cada fila representa una apuesta independiente.

CREATE TABLE public.MatchBets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userId UUID NOT NULL
        REFERENCES public.Users(id)
        ON DELETE CASCADE,
    matchId TEXT NOT NULL
        REFERENCES public.MatchResults(matchId)
        ON DELETE CASCADE,
    betGoalTeam1 INT NOT NULL,
    betGoalTeam2 INT NOT NULL,
    penaltyWinnerTeam INT CHECK (
    penaltyWinnerTeam IS NULL
    OR penaltyWinnerTeam IN (1, 2)
    ),
    hasPaidExtraPool BOOLEAN NOT NULL DEFAULT FALSE,
    createdAt TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updatedAt TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (
        userId,
        matchId,
        betGoalTeam1,
        betGoalTeam2
    )
);

-- Si un usuario hace una apuesta extra a un partido
CREATE TABLE public.ExtraPoolEntries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    betId BIGINT NOT NULL
        REFERENCES public.MatchBets(id)
        ON DELETE CASCADE,
    amountBs DECIMAL(10,2) NOT NULL,
    receiptUrl TEXT,
    paymentValidated BOOLEAN NOT NULL DEFAULT FALSE,
    createdAt TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (betId)
);

-- =====================================================
--  MATCH POOLS
-- =====================================================
-- Guarda info de las pozas diarias por partido
-- Cuanto es el porcentaje para ese partido para el mantenimiento (5% o 10%)
-- Cuanto es el total registrado de todos los participantes para esta poza diaria
-- Si nadie ganó cuanto se añade del anterior partido al nuevo
-- Cuanto se distribuye al o a los ganadores
-- Cuanto queda para el mantenimiento de la plataforma

CREATE TABLE public.MatchPools (
    matchId TEXT PRIMARY KEY
        REFERENCES public.MatchResults(matchId)
        ON DELETE CASCADE,
    entryFeeBs DECIMAL(10,2) NOT NULL,
    maintenancePercentage DECIMAL(5,2) NOT NULL,
    rolloverAmountBs DECIMAL(10,2) NOT NULL DEFAULT 0,
    totalCollectedBs DECIMAL(10,2) NOT NULL DEFAULT 0,
    totalDistributedBs DECIMAL(10,2) NOT NULL DEFAULT 0,
    maintenanceAmountBs DECIMAL(10,2) NOT NULL DEFAULT 0,
    minimumPlayers INT NOT NULL DEFAULT 3,
    poolStatus TEXT NOT NULL DEFAULT 'OPEN'
        CHECK (poolStatus IN ('OPEN', 'COMPLETED', 'CANCELED', 'ROLLED_OVER')),
    -- Si no se llega al mínimo de jugadores, se cancela la poza
    -- y se asigna un crédito a cada participante en users.availablePoolCredits
    processedAt TIMESTAMPTZ,
    createdAt TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =====================================================
--  WINNERS BETS
-- =====================================================
-- Una predicción de podio por usuario.

CREATE TABLE public.WinnersBets (
    userId UUID PRIMARY KEY
        REFERENCES public.Users(id)
        ON DELETE CASCADE,
    winner1stPlace TEXT NOT NULL,
    winner2ndPlace TEXT NOT NULL,
    winner3rdPlace TEXT NOT NULL,
    createdAt TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updatedAt TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =====================================================
-- CASH INFLOW
-- =====================================================
-- Registro de dinero recibido.
-- No representa apuestas.
-- Representa movimientos financieros.

CREATE TABLE public.CashInflow (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userId UUID
        REFERENCES public.Users(id),
    createdBy UUID
        REFERENCES public.Users(id),
    amountBs DECIMAL(10,2) NOT NULL,
    concept TEXT NOT NULL,
    receiptUrl TEXT, -- Inscripción inicial
    createdAt TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =====================================================
-- DAILY PAYOUTS
-- =====================================================
-- Registro de premios pagados.

CREATE TABLE public.DailyPayouts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matchId TEXT
        REFERENCES public.MatchResults(matchId),
    userId UUID
        REFERENCES public.Users(id),
    amountPaidBs DECIMAL(10,2) NOT NULL,
    paymentStatus BOOLEAN NOT NULL DEFAULT FALSE,
    payoutDate TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    paidAt TIMESTAMPTZ DEFAULT NULL
);


-- =====================================================
-- TOURNAMENT RANKING
-- =====================================================
-- CRanking con más puntos
CREATE TABLE public.TournamentRanking (
    userId UUID PRIMARY KEY
        REFERENCES public.Users(id)
        ON DELETE CASCADE,
    points INT NOT NULL DEFAULT 0,
    updatedAt TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =====================================================
-- INDEXES
-- =====================================================

CREATE INDEX idx_matchbets_userid
ON public.MatchBets(userId);

CREATE INDEX idx_matchbets_matchid
ON public.MatchBets(matchId);

CREATE INDEX idx_cashinflow_userid
ON public.CashInflow(userId);

CREATE INDEX idx_dailypayouts_userid
ON public.DailyPayouts(userId);

CREATE INDEX idx_extrapoolentries_betid
ON public.ExtraPoolEntries(betId);

CREATE INDEX idx_ranking_userid
ON public.TournamentRanking(userId);

-- =====================================================
-- ROW LEVEL SECURITY
-- =====================================================

-- Enable RLS on all tables
ALTER TABLE public.Users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.MatchResults ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.MatchBets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ExtraPoolEntries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.MatchPools ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.WinnersBets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.CashInflow ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.DailyPayouts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.TournamentRanking ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.authorized_users ENABLE ROW LEVEL SECURITY;

-- Users: users can read their own row; admins can read all
CREATE POLICY "Users can read own row"
    ON public.Users
    FOR SELECT
    TO authenticated
    USING (auth.uid() = id);

CREATE POLICY "Admins can read all users"
    ON public.Users
    FOR SELECT
    TO authenticated
    USING (EXISTS (
        SELECT 1 FROM public.Users u
        WHERE u.id = auth.uid() AND u.isAdmin = TRUE
    ));

-- Users: users can update their own row (except hasPaidEntry and isAdmin)
CREATE POLICY "Users can update own row"
    ON public.Users
    FOR UPDATE
    TO authenticated
    USING (auth.uid() = id)
    WITH CHECK (auth.uid() = id);

-- MatchResults: any authenticated user can read
CREATE POLICY "Authenticated users can read match results"
    ON public.MatchResults
    FOR SELECT
    TO authenticated
    USING (TRUE);

-- MatchBets: users can read their own bets
CREATE POLICY "Users can read own bets"
    ON public.MatchBets
    FOR SELECT
    TO authenticated
    USING (userId = auth.uid());

-- MatchBets: users can insert their own bets
CREATE POLICY "Users can insert own bets"
    ON public.MatchBets
    FOR INSERT
    TO authenticated
    WITH CHECK (userId = auth.uid());

-- MatchBets: users can update their own bets
CREATE POLICY "Users can update own bets"
    ON public.MatchBets
    FOR UPDATE
    TO authenticated
    USING (userId = auth.uid())
    WITH CHECK (userId = auth.uid());

-- MatchBets: users can delete their own bets
CREATE POLICY "Users can delete own bets"
    ON public.MatchBets
    FOR DELETE
    TO authenticated
    USING (userId = auth.uid());

-- ExtraPoolEntries: users can read their own entries
CREATE POLICY "Users can read own pool entries"
    ON public.ExtraPoolEntries
    FOR SELECT
    TO authenticated
    USING (EXISTS (
        SELECT 1 FROM public.MatchBets b
        WHERE b.id = betId AND b.userId = auth.uid()
    ));

-- ExtraPoolEntries: users can insert entries for their own bets
CREATE POLICY "Users can insert own pool entries"
    ON public.ExtraPoolEntries
    FOR INSERT
    TO authenticated
    WITH CHECK (EXISTS (
        SELECT 1 FROM public.MatchBets b
        WHERE b.id = betId AND b.userId = auth.uid()
    ));

-- MatchPools: any authenticated user can read
CREATE POLICY "Authenticated users can read match pools"
    ON public.MatchPools
    FOR SELECT
    TO authenticated
    USING (TRUE);

-- WinnersBets: any authenticated user can read
CREATE POLICY "Authenticated users can read winners bets"
    ON public.WinnersBets
    FOR SELECT
    TO authenticated
    USING (TRUE);

-- WinnersBets: users can insert/update their own podium prediction
CREATE POLICY "Users can insert own winners bet"
    ON public.WinnersBets
    FOR INSERT
    TO authenticated
    WITH CHECK (userId = auth.uid());

CREATE POLICY "Users can update own winners bet"
    ON public.WinnersBets
    FOR UPDATE
    TO authenticated
    USING (userId = auth.uid())
    WITH CHECK (userId = auth.uid());

-- CashInflow: users can read their own records
CREATE POLICY "Users can read own cash inflow"
    ON public.CashInflow
    FOR SELECT
    TO authenticated
    USING (userId = auth.uid());

-- DailyPayouts: users can read their own payouts
CREATE POLICY "Users can read own payouts"
    ON public.DailyPayouts
    FOR SELECT
    TO authenticated
    USING (userId = auth.uid());

-- TournamentRanking: any authenticated user can read
CREATE POLICY "Authenticated users can read tournament ranking"
    ON public.TournamentRanking
    FOR SELECT
    TO authenticated
    USING (TRUE);

-- authorized_users: authenticated users can read their own row
CREATE POLICY "Authenticated users can read own authorized record"
    ON public.authorized_users
    FOR SELECT
    TO authenticated
    USING (email = auth.jwt() ->> 'email');

-- =====================================================
-- AUTH TRIGGER: auto-create Users row on signup
-- =====================================================

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    auth_user public.authorized_users%ROWTYPE;
BEGIN
    SELECT * INTO auth_user
    FROM public.authorized_users
    WHERE email = NEW.email
      AND active = TRUE;

    IF FOUND THEN
        INSERT INTO public.users (
            id,
            email,
            name,
            alias,
            "haspaidentry",
            "isadmin"
        )
        VALUES (
            NEW.id,
            auth_user.email,
            auth_user.name,
            auth_user.alias,
            FALSE,
            auth_user.is_admin
        );
    END IF;

    RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_new_user();